export const postData = [
    {
        id:1,
        firstName:"Tony",
        lastName:"Stark", 
        userName:"jk",
        email:"jarvis@gmail.com",
        likes:3,
        comments:89,
        isFollew:true,
        profilePic:"/images/profilepic.png",
        postImage:"/images/ironmanpost.jpg"
    },
    {
        id:2,
        firstName:"cristiano",
        lastName:"ronaldo", 
        userName:"cr7",
        email:"cristiano@gmail.com",
        likes:3,
        comments:89,
        isFollew:true,
        profilePic:"/images/ronaldo.jpeg",
        postImage:"/images/ronaldo.jpg"
    },
    {
        id:3,
        firstName:"Peter",
        lastName:"Parker", 
        userName:"spider_man",
        email:"peter@gmail.com",
        likes:3,
        comments:89,
        isFollew:true,
        profilePic:"/images/spidermanprofile.jpeg",
        postImage:"/images/spidermanprofile.jpeg"
    },
    {
        id:4,
        firstName:"Zyan",
        lastName:"Malik", 
        userName:"zyan",
        email:"zyan@gmail.com",
        likes:3,
        comments:89,
        isFollew:true,
        profilePic:"/images/zyanprofilepic.jpeg",
        postImage:"/images/zyanpost.jpg"
    },
]