import Head from 'next/head'
import Image from 'next/image'
import CallList from '../components/CallList/CallList'
import styles from '../styles/Home.module.css'
import Header from '../components/header/Header'
import Login from './login'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />

      {/* <CallList /> */}
      {/* <Header  /> */}
      
    </div>
  )
}
